---
title: "TS hw.3"
author: "L, YanShao"
date: "2022-11-11"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

針對 HW2 所收集的 3 個大盤指數與 3 個相關匯率指數，執行以下步驟：
1. 針對每一筆原始資料，檢定是否需要差分
2. 針對每一筆資料，討論是否具有週期性
3. 分別對每一筆資料建立一適合的時間序列模型

```{r lib, include=FALSE}
library(zoo)
library(xts)
library(TTR)
library(quantmod)
library(ggplot2)
library(magrittr)
library(broom)
library(qpcR)   
library(fpp2)
library(fUnitRoots)
library(stats)
```



```{r warning=FALSE}
getSymbols("^GSPC", from ='2012-10-12', to = '2022-10-12')
GSPC <- as.xts(data.frame(GSPC = GSPC[, "GSPC.Adjusted"]))
names(GSPC) = c("GSPC")
index(GSPC) = as.Date(index(GSPC))
logrt.GSPC <- apply( log(GSPC) , 2 , diff )*100
rt.GSPC <- (exp(apply( log(GSPC) , 2 , diff ))-1)*100

getSymbols("^TWII", from = '2012-10-12', to = '2022-10-12')
TWII <- as.xts(data.frame(TWII = TWII[, "TWII.Adjusted"]))
TWII <- na.omit(TWII)
names(TWII) = c("TWII")
index(TWII) = as.Date(index(TWII))
logrt.TWII <- apply( log(TWII) , 2 , diff )*100
rt.TWII <- (exp(apply( log(TWII) , 2 , diff ))-1)*100

getSymbols("^FTSE", from = '2012-10-12', to = '2022-10-12')
FTSE<-as.xts(data.frame(FTSE = FTSE[, "FTSE.Adjusted"]))
FTSE<-na.omit(FTSE)
names(FTSE) = c("FTSE")
index(FTSE) = as.Date(index(FTSE))
logrt.FTSE<-apply( log(FTSE) , 2 , diff )*100
rt.FTSE<-(exp(apply( log(FTSE) , 2 , diff ))-1)*100

getSymbols("USDTWD=X", from = '2012-10-12', to = '2022-10-12')
USDTWD<-as.xts(data.frame(`USDTWD=X` = `USDTWD=X`[, paste0("USDTWD=X.Adjusted")]))
USDTWD<-na.omit(USDTWD)
names(USDTWD) = c("USDTWD")
index(USDTWD) = as.Date(index(USDTWD))
USDTWD$USDTWD[578,]<-30.13
logrt.USDTWD<-apply( log(USDTWD) , 2 , diff )*100
rt.USDTWD<-(exp(apply( log(USDTWD) , 2 , diff ))-1)*100

getSymbols("GBPTWD=X", from = '2012-10-12', to = '2022-10-12')
GBPTWD<-as.xts(data.frame(`GBPTWD=X` = `GBPTWD=X`[, paste0("GBPTWD=X.Adjusted")]))
GBPTWD<-na.omit(GBPTWD)
names(GBPTWD) = c("GBPTWD")
index(GBPTWD) = as.Date(index(GBPTWD))
logrt.GBPTWD<-apply( log(GBPTWD) , 2 , diff )*100
rt.GBPTWD<-(exp(apply( log(GBPTWD) , 2 , diff ))-1)*100

getSymbols("USDGBP=X", from = '2012-10-12', to = '2022-10-12')
USDGBP<-as.xts(data.frame(`USDGBP=X` = `USDGBP=X`[, paste0("USDGBP=X.Adjusted")]))
USDGBP<-na.omit(USDGBP)
names(USDGBP) = c("USDGBP")
index(USDGBP) = as.Date(index(USDGBP))
logrt.USDGBP<-apply( log(USDGBP) , 2 , diff )*100
rt.USDGBP<-(exp(apply( log(USDGBP) , 2 , diff ))-1)*100

res <- function(data){
  
  acf(data, lag.max = 20)
#  title(paste("ACF","of",name), line = 0)
  
  pacf(data, lag.max = 20)
#  title(paste("PACF","of",name), line = 0.3)
  
}

Price_data <- list(GSPC, FTSE, TWII, USDTWD, GBPTWD, USDGBP)

```





```{r , warning=FALSE}
for (i in c(1,3)) {
  plot(Price_data[[i]],main=names(Price_data[[i]]))
}# it don't show ???

plot(Price_data[[1]],main=names(Price_data[[1]]))
adfTest(Price_data[[1]],type = "ct")
res(Price_data[[1]])

plot(diff(Price_data[[1]]),main=names(Price_data[[1]]))
adfTest(diff(Price_data[[1]]),type = "ct")
res(diff(Price_data[[1]])[-1])
```
H_o:beta=1 vs H1:beta<1



```{r}
plot(Price_data[[2]],main=names(Price_data[[2]]))
adfTest(Price_data[[2]],type = "ct")
res(Price_data[[2]])# Look seasonal (maybe diff by period?)
```


```{r}
plot(Price_data[[3]],main=names(Price_data[[3]]))
adfTest(Price_data[[3]],type = "ct")
res(Price_data[[3]])

plot(diff(Price_data[[3]]),main=names(Price_data[[3]]))
adfTest(diff(Price_data[[3]]),type = "ct")
res(diff(Price_data[[3]])[-1])# Need diff
```


```{r}
plot(Price_data[[4]],main=names(Price_data[[4]]))
adfTest(Price_data[[4]],type = "ct")
adfTest(Price_data[[4]],type = "nc")
res(Price_data[[4]])

plot(diff(Price_data[[4]]),main=names(Price_data[[4]]))
res(diff(Price_data[[4]])[-1])# overdiff
```




```{r}
plot(Price_data[[5]],main=names(Price_data[[5]]))
adfTest(Price_data[[5]],type = "ct")
adfTest(Price_data[[5]],type = "c")
res(Price_data[[5]])

plot(diff(Price_data[[5]]),main=names(Price_data[[5]]))
adfTest(diff(Price_data[[5]]),type = "ct")
adfTest(diff(Price_data[[5]]),type = "c")
res(diff(Price_data[[5]])[-1])# overdiff
```



```{r}
plot(Price_data[[6]],main=names(Price_data[[6]]))
adfTest(Price_data[[6]],type = "ct")
adfTest(Price_data[[6]],type = "c")
res(Price_data[[6]])

plot(diff(Price_data[[5]]),main=names(Price_data[[5]]))
adfTest(diff(Price_data[[5]]),type = "ct")
adfTest(diff(Price_data[[5]]),type = "c")
res(diff(Price_data[[6]])[-1])
```

